CREATE TABLE IF NOT EXISTS PRODUCT_TABLE(
PRODUCT_ID VARCHAR(10),
PRODUCT_NAME VARCHAR(20),
MANUFACTURER_ID INTEGER(10),
CREATED TIMESTAMP,
UPDATED TIMESTAMP,
PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE IF NOT EXISTS USER_TABLE(
USER_ID VARCHAR(10),
USER_EMAIL VARCHAR(50),
MOBILE VARCHAR(12),
CREATED TIMESTAMP,
UPDATED TIMESTAMP,
PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS ORDER_TABLE(
ORDER_ID VARCHAR(36),
PRODUCT_ID VARCHAR(10),
USER_ID VARCHAR(10),
ORDER_QTY INTEGER(10),
CREATED TIMESTAMP,
UPDATED TIMESTAMP,
PRIMARY KEY (ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT_TABLE (PRODUCT_ID),
FOREIGN KEY (USER_ID) REFERENCES USER_TABLE (USER_ID)
);
