INSERT INTO PRODUCT_TABLE (PRODUCT_ID, PRODUCT_NAME, MANUFACTURER_ID, CREATED, UPDATED) VALUES ('PR01', 'Samsung TV', 1, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO PRODUCT_TABLE (PRODUCT_ID, PRODUCT_NAME, MANUFACTURER_ID, CREATED, UPDATED) VALUES ('PR02', 'LG Refrigerator', 2, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

INSERT INTO USER_TABLE (USER_ID, USER_EMAIL, MOBILE, CREATED, UPDATED) VALUES ('US001', 'arjun@gmail.com', 7894563218, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());
INSERT INTO USER_TABLE (USER_ID, USER_EMAIL, MOBILE, CREATED, UPDATED) VALUES ('US002', 'rahul@gmail.com', 9994156562, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());